### ISSUE TITLE
Service_identity module missing

### ISSUE THREAD

**Issue by James-Crean** [UV-CDAT/vcs-js#36]
When doing a clean/fresh install it seems that Linux (and sometimes Mac) report that twisted can't find the service_identity module. 

Doing `pip install service_identity` fixes the issue, but we should make sure that it is included during the set up. Is it missing from a dependency list somewhere?

**Comment by scottwittenburg** [comment]
So I did a little looking and it seems the version of VTK we have picked in the `uv-cdat/conda-recipes` project is a SHA from just after we moved to [wslink](https://github.com/Kitware/wslink), and just before that (and all other) ThirdParty modules were removed from VTK.  When we move forward to a new version of VTK, we will likely need a `requirements.txt` for the Python part of this project in order to bring in those modules which used to live in the VTK ThirdParty directory (e.g. Twisted, Autobahn) , and at that point, it will be a good time to add the `sevice_identity` module as a dependency.

I have created a [PR](https://github.com/Kitware/wslink/pull/7) over on the `wslink` repo which could make this a titch easier on the `vcs-js` end.

But we can leave this open until the issue is resolved to the satisfaction of all.

**Comment by doutriaux1** [comment]
@scottwittenburg the biggest issue I foresee with this, is that we are using OpenGL1 and it is removed from vtk... So we can't even build master any longer... Once this is fixed we can review this issue.

**Comment by scottwittenburg** [comment]
Sounds good @doutriaux1, and if we need to do something more quickly we can always just add a `requirements.txt` to this project and only put `service_identity` in it for the time being.

**Comment by James-Crean** [comment]
@scottwittenburg I like the idea of adding a `requirements.txt` for now. Since we are trying to get users to install and try vcdat out, I want to avoid problems that might give them a bad first impression. 

@doutriaux1 Is a requirements file alright with you until a formal fix is in place?

**Comment by James-Crean** [comment]
@scottwittenburg, Where are we on this issue?

**Comment by scottwittenburg** [comment]
Well, I haven't done anything since my last comments.  But this doesn't actually break anything, so maybe it boils down to: "what are we willing to do in order to avoid that warning getting printed?"  I can add a `requirements.txt`, but this module isn't technically a requirement.  Once we can use a new VTK, then we will *need* a requirements file, because there will then be python modules we require which VTK is no longer bringing.

I guess I'm kind of on the fence.  I can add the file, but it seems a little weird.

**Comment by James-Crean** [comment]
If you don't believe it makes sense then we don't need to. I just double checked and a fresh install of vcdat gives the warning, but does not cause the application to fail. I will leave it open for now, and when the new VTK comes out we can revisit this then. That sound alright to you?

**Comment by scottwittenburg** [comment]
Yes, I think that makes sense, thanks.

**Comment by scottwittenburg** [comment]
@doutriaux1 I'm testing this project out with my `context2d-alpha-release` branch, and noticed that we have finally come to the point of needing to address this issue.  I'm setting up a `requirements.txt` to note the python modules needed.  The first one I added was:

```
wslink[security]
```

That covers the issue @James-Crean first reported here and gets me some modules like `twisted` and `autobahn`, etc... that used to come with VTK.  Now I have hit another import error:

```
Program stderr: Traceback (most recent call last):
  File "/data/scott/projects/uvcdat/vcs-js/scripts/vcs-test-server.py", line 14, in <module>
    from vcs_server.Visualizer import Visualizer
  File "/data/scott/projects/uvcdat/vcs-js/vcs_server/Visualizer.py", line 13, in <module>
    import compute_graph
ImportError: No module named compute_graph
```

Do you know where I can get that module?  There are a lot of projects under `cdat`, two of them look promising: `compute_graph` and `cdat_compute_graph`.

ping @danlipsa @aashish24

**Comment by doutriaux1** [comment]
should be avail via conda. but github.com/cdat/compute_graph

**Comment by scottwittenburg** [comment]
Thanks @doutriaux1 and @James-Crean for the information.
